service: sls-demo
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  iam:
    role:
      statements:
        - ${file(./iam/SongsTableIAM.yml):SongsTableIAM}
  environment:
    SONGS_TABLE_NAME: ${self:custom.SongsTable.name}

resources:
  Resources: 
    SongsTable: ${file(./resources/SongsTable.yml):SongsTable}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  createSong:
    handler: src/handlers.createHandler
    events:
      - httpApi:
          path: /songs
          method: post

custom:
  SongsTable:
    name: 
      Ref: SongsTable
    arn: !GetAtt SongsTable.Arn
