service: sls-demo
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  iam:
    role:
      statements:
        - ${file(./iam/SongsTableIAM.yml):SongsTableIAM}
  environment:
    SONGS_TABLE_NAME: ${self:custom.SongsTable.name}

resources:
  Resources: 
    SongsTable: ${file(./resources/SongsTable.yml):SongsTable}

functions:
  createSong:
    handler: src/handlers/createSong.handler
    events:
      - httpApi:
          path: /songs
          method: post
  findSongs:
    handler: src/handlers/findSongs.handler
    events:
      - httpApi:
          path: /songs
          method: get
  getSong:
    handler: src/handlers/getSong.handler
    events:
      - httpApi:
          path: /songs/{id}
          method: get

custom:
  SongsTable:
    name: 
      Ref: SongsTable
    arn: !GetAtt SongsTable.Arn
